# Generated by Django 4.2 on 2023-05-21 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_player_looser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Name'),
        ),
    ]
